import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { SideNav } from '@/components/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid grid-cols-[480px_1fr]">
      <SideNav />
      {/* NOTE: SPAページはPageHeaderとコンテンツ部分が必ず入る前提 */}
      <div className="grid grid-rows-[max-content_1fr]">{children}</div>
    </main>
  );
}
